<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project"
    nsURI="http:///org/devzuz/q/project.ecore" nsPrefix="org.devzuz.q.project">
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactComposition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactType" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactManifestPartsByType"
        upperBound="-1" eType="#//URIToArtifactManifestPartMapEntry" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactManifestPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunityInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectWebSite" eType="#//URL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="downloadLocations" upperBound="-1"
        eType="#//URIToURLMapEntry" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mailingListServices" upperBound="-1"
        eType="#//EStringToInfrastructuralServiceMapEntry" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scmService" eType="#//InfrastructuralService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueTrackerService" eType="#//InfrastructuralService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependencyScheme" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectKey" eType="#//ProjectKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactClassifier" eType="#//ArtifactClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructuralService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceId" eType="#//InfrastructuralServiceId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submitInterfaces" upperBound="-1"
        eType="#//URIToInfrastructuralServiceInterfaceMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryInterfaces" upperBound="-1"
        eType="#//URIToInfrastructuralServiceInterfaceMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="browseInterfaces" upperBound="-1"
        eType="#//URIToInfrastructuralServiceInterfaceMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maintenanceInterfaces"
        upperBound="-1" eType="#//URIToInfrastructuralServiceInterfaceMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructuralServiceId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeURI" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeQualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructuralServiceInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceType" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="License">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uRL" eType="#//URL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicability" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessagingSystemId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeURI" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemQualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webSite" eType="#//URL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organizationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timezone" eType="#//TimeZone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nicknames" upperBound="-1"
        eType="#//MessagingSystemIdToEStringMapEntry" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identification" eType="#//ProjectKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentProject" eType="#//ProjectKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizationInfo" eType="#//OrganizationInfo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communityInfo" eType="#//CommunityInfo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="licenses" upperBound="-1"
        eType="#//License"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectClassifications"
        upperBound="-1" eType="#//ProjectClassification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactComposition" eType="#//ArtifactComposition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolConfigurationByType"
        upperBound="-1" eType="#//ToolIdToToolConfigurationMapEntry" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributors" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developers" upperBound="-1"
        eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectClassification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classificationSystemId"
        eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionSpec" eType="#//Version"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolId" eType="#//ToolId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeURI" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeQualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionScheme" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="java.net.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="URIToArtifactManifestPartMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ArtifactManifestPart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URL" instanceClassName="java.net.URL"/>
  <eClassifiers xsi:type="ecore:EClass" name="URIToURLMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//URL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToInfrastructuralServiceMapEntry"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//InfrastructuralService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URIToInfrastructuralServiceInterfaceMapEntry"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//InfrastructuralServiceInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TimeZone" instanceClassName="java.util.TimeZone"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessagingSystemIdToEStringMapEntry"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//MessagingSystemId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolIdToToolConfigurationMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//ToolId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ToolConfiguration"/>
  </eClassifiers>
</ecore:EPackage>
