/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.apache.maven.pom400.util.mavenAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class mavenItemProviderAdapterFactory extends mavenAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public mavenItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);		
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Activation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivationItemProvider activationItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Activation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivationAdapter() {
		if (activationItemProvider == null) {
			activationItemProvider = new ActivationItemProvider(this);
		}

		return activationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ActivationFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivationFileItemProvider activationFileItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ActivationFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivationFileAdapter() {
		if (activationFileItemProvider == null) {
			activationFileItemProvider = new ActivationFileItemProvider(this);
		}

		return activationFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ActivationOS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivationOSItemProvider activationOSItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ActivationOS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivationOSAdapter() {
		if (activationOSItemProvider == null) {
			activationOSItemProvider = new ActivationOSItemProvider(this);
		}

		return activationOSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ActivationProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivationPropertyItemProvider activationPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ActivationProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivationPropertyAdapter() {
		if (activationPropertyItemProvider == null) {
			activationPropertyItemProvider = new ActivationPropertyItemProvider(this);
		}

		return activationPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Build} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildItemProvider buildItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Build}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createBuildAdapter() {
		if (buildItemProvider == null) {
			buildItemProvider = new BuildItemProvider(this);
		}

		return buildItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.BuildBase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildBaseItemProvider buildBaseItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.BuildBase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createBuildBaseAdapter() {
		if (buildBaseItemProvider == null) {
			buildBaseItemProvider = new BuildBaseItemProvider(this);
		}

		return buildBaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.CiManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CiManagementItemProvider ciManagementItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.CiManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCiManagementAdapter() {
		if (ciManagementItemProvider == null) {
			ciManagementItemProvider = new CiManagementItemProvider(this);
		}

		return ciManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ConfigurationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationTypeItemProvider configurationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ConfigurationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConfigurationTypeAdapter() {
		if (configurationTypeItemProvider == null) {
			configurationTypeItemProvider = new ConfigurationTypeItemProvider(this);
		}

		return configurationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ConfigurationType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationType1ItemProvider configurationType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ConfigurationType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConfigurationType1Adapter() {
		if (configurationType1ItemProvider == null) {
			configurationType1ItemProvider = new ConfigurationType1ItemProvider(this);
		}

		return configurationType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ConfigurationType2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationType2ItemProvider configurationType2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ConfigurationType2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConfigurationType2Adapter() {
		if (configurationType2ItemProvider == null) {
			configurationType2ItemProvider = new ConfigurationType2ItemProvider(this);
		}

		return configurationType2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ConfigurationType3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationType3ItemProvider configurationType3ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ConfigurationType3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConfigurationType3Adapter() {
		if (configurationType3ItemProvider == null) {
			configurationType3ItemProvider = new ConfigurationType3ItemProvider(this);
		}

		return configurationType3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ConfigurationType4} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationType4ItemProvider configurationType4ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ConfigurationType4}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConfigurationType4Adapter() {
		if (configurationType4ItemProvider == null) {
			configurationType4ItemProvider = new ConfigurationType4ItemProvider(this);
		}

		return configurationType4ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Contributor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContributorItemProvider contributorItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Contributor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createContributorAdapter() {
		if (contributorItemProvider == null) {
			contributorItemProvider = new ContributorItemProvider(this);
		}

		return contributorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ContributorsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContributorsTypeItemProvider contributorsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ContributorsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createContributorsTypeAdapter() {
		if (contributorsTypeItemProvider == null) {
			contributorsTypeItemProvider = new ContributorsTypeItemProvider(this);
		}

		return contributorsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DependenciesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependenciesTypeItemProvider dependenciesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DependenciesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependenciesTypeAdapter() {
		if (dependenciesTypeItemProvider == null) {
			dependenciesTypeItemProvider = new DependenciesTypeItemProvider(this);
		}

		return dependenciesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DependenciesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependenciesType1ItemProvider dependenciesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DependenciesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependenciesType1Adapter() {
		if (dependenciesType1ItemProvider == null) {
			dependenciesType1ItemProvider = new DependenciesType1ItemProvider(this);
		}

		return dependenciesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DependenciesType2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependenciesType2ItemProvider dependenciesType2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DependenciesType2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependenciesType2Adapter() {
		if (dependenciesType2ItemProvider == null) {
			dependenciesType2ItemProvider = new DependenciesType2ItemProvider(this);
		}

		return dependenciesType2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DependenciesType3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependenciesType3ItemProvider dependenciesType3ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DependenciesType3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependenciesType3Adapter() {
		if (dependenciesType3ItemProvider == null) {
			dependenciesType3ItemProvider = new DependenciesType3ItemProvider(this);
		}

		return dependenciesType3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Dependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependencyItemProvider dependencyItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Dependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependencyAdapter() {
		if (dependencyItemProvider == null) {
			dependencyItemProvider = new DependencyItemProvider(this);
		}

		return dependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DependencyManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependencyManagementItemProvider dependencyManagementItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DependencyManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependencyManagementAdapter() {
		if (dependencyManagementItemProvider == null) {
			dependencyManagementItemProvider = new DependencyManagementItemProvider(this);
		}

		return dependencyManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DeploymentRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentRepositoryItemProvider deploymentRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DeploymentRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDeploymentRepositoryAdapter() {
		if (deploymentRepositoryItemProvider == null) {
			deploymentRepositoryItemProvider = new DeploymentRepositoryItemProvider(this);
		}

		return deploymentRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Developer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeveloperItemProvider developerItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Developer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDeveloperAdapter() {
		if (developerItemProvider == null) {
			developerItemProvider = new DeveloperItemProvider(this);
		}

		return developerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DevelopersType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DevelopersTypeItemProvider developersTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DevelopersType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDevelopersTypeAdapter() {
		if (developersTypeItemProvider == null) {
			developersTypeItemProvider = new DevelopersTypeItemProvider(this);
		}

		return developersTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DistributionManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DistributionManagementItemProvider distributionManagementItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DistributionManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDistributionManagementAdapter() {
		if (distributionManagementItemProvider == null) {
			distributionManagementItemProvider = new DistributionManagementItemProvider(this);
		}

		return distributionManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ExcludesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExcludesTypeItemProvider excludesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ExcludesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExcludesTypeAdapter() {
		if (excludesTypeItemProvider == null) {
			excludesTypeItemProvider = new ExcludesTypeItemProvider(this);
		}

		return excludesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Exclusion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExclusionItemProvider exclusionItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Exclusion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExclusionAdapter() {
		if (exclusionItemProvider == null) {
			exclusionItemProvider = new ExclusionItemProvider(this);
		}

		return exclusionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ExclusionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExclusionsTypeItemProvider exclusionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ExclusionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExclusionsTypeAdapter() {
		if (exclusionsTypeItemProvider == null) {
			exclusionsTypeItemProvider = new ExclusionsTypeItemProvider(this);
		}

		return exclusionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ExecutionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionsTypeItemProvider executionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ExecutionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExecutionsTypeAdapter() {
		if (executionsTypeItemProvider == null) {
			executionsTypeItemProvider = new ExecutionsTypeItemProvider(this);
		}

		return executionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Extension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionItemProvider extensionItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Extension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtensionAdapter() {
		if (extensionItemProvider == null) {
			extensionItemProvider = new ExtensionItemProvider(this);
		}

		return extensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ExtensionsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionsTypeItemProvider extensionsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ExtensionsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtensionsTypeAdapter() {
		if (extensionsTypeItemProvider == null) {
			extensionsTypeItemProvider = new ExtensionsTypeItemProvider(this);
		}

		return extensionsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.FiltersType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FiltersTypeItemProvider filtersTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.FiltersType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFiltersTypeAdapter() {
		if (filtersTypeItemProvider == null) {
			filtersTypeItemProvider = new FiltersTypeItemProvider(this);
		}

		return filtersTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.FiltersType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FiltersType1ItemProvider filtersType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.FiltersType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFiltersType1Adapter() {
		if (filtersType1ItemProvider == null) {
			filtersType1ItemProvider = new FiltersType1ItemProvider(this);
		}

		return filtersType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.GoalsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoalsTypeItemProvider goalsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.GoalsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGoalsTypeAdapter() {
		if (goalsTypeItemProvider == null) {
			goalsTypeItemProvider = new GoalsTypeItemProvider(this);
		}

		return goalsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.GoalsType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoalsType1ItemProvider goalsType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.GoalsType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGoalsType1Adapter() {
		if (goalsType1ItemProvider == null) {
			goalsType1ItemProvider = new GoalsType1ItemProvider(this);
		}

		return goalsType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.IncludesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludesTypeItemProvider includesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.IncludesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIncludesTypeAdapter() {
		if (includesTypeItemProvider == null) {
			includesTypeItemProvider = new IncludesTypeItemProvider(this);
		}

		return includesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.IssueManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IssueManagementItemProvider issueManagementItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.IssueManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIssueManagementAdapter() {
		if (issueManagementItemProvider == null) {
			issueManagementItemProvider = new IssueManagementItemProvider(this);
		}

		return issueManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.License} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LicenseItemProvider licenseItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.License}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLicenseAdapter() {
		if (licenseItemProvider == null) {
			licenseItemProvider = new LicenseItemProvider(this);
		}

		return licenseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.LicensesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LicensesTypeItemProvider licensesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.LicensesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLicensesTypeAdapter() {
		if (licensesTypeItemProvider == null) {
			licensesTypeItemProvider = new LicensesTypeItemProvider(this);
		}

		return licensesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.MailingList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailingListItemProvider mailingListItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.MailingList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMailingListAdapter() {
		if (mailingListItemProvider == null) {
			mailingListItemProvider = new MailingListItemProvider(this);
		}

		return mailingListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.MailingListsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MailingListsTypeItemProvider mailingListsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.MailingListsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMailingListsTypeAdapter() {
		if (mailingListsTypeItemProvider == null) {
			mailingListsTypeItemProvider = new MailingListsTypeItemProvider(this);
		}

		return mailingListsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ModulesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModulesTypeItemProvider modulesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ModulesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createModulesTypeAdapter() {
		if (modulesTypeItemProvider == null) {
			modulesTypeItemProvider = new ModulesTypeItemProvider(this);
		}

		return modulesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ModulesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModulesType1ItemProvider modulesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ModulesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createModulesType1Adapter() {
		if (modulesType1ItemProvider == null) {
			modulesType1ItemProvider = new ModulesType1ItemProvider(this);
		}

		return modulesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Notifier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotifierItemProvider notifierItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Notifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNotifierAdapter() {
		if (notifierItemProvider == null) {
			notifierItemProvider = new NotifierItemProvider(this);
		}

		return notifierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.NotifiersType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotifiersTypeItemProvider notifiersTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.NotifiersType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNotifiersTypeAdapter() {
		if (notifiersTypeItemProvider == null) {
			notifiersTypeItemProvider = new NotifiersTypeItemProvider(this);
		}

		return notifiersTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Organization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrganizationItemProvider organizationItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Organization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOrganizationAdapter() {
		if (organizationItemProvider == null) {
			organizationItemProvider = new OrganizationItemProvider(this);
		}

		return organizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.OtherArchivesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OtherArchivesTypeItemProvider otherArchivesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.OtherArchivesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOtherArchivesTypeAdapter() {
		if (otherArchivesTypeItemProvider == null) {
			otherArchivesTypeItemProvider = new OtherArchivesTypeItemProvider(this);
		}

		return otherArchivesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Parent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParentItemProvider parentItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Parent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createParentAdapter() {
		if (parentItemProvider == null) {
			parentItemProvider = new ParentItemProvider(this);
		}

		return parentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Plugin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginItemProvider pluginItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Plugin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginAdapter() {
		if (pluginItemProvider == null) {
			pluginItemProvider = new PluginItemProvider(this);
		}

		return pluginItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginExecution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginExecutionItemProvider pluginExecutionItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginExecution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginExecutionAdapter() {
		if (pluginExecutionItemProvider == null) {
			pluginExecutionItemProvider = new PluginExecutionItemProvider(this);
		}

		return pluginExecutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginManagementItemProvider pluginManagementItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginManagementAdapter() {
		if (pluginManagementItemProvider == null) {
			pluginManagementItemProvider = new PluginManagementItemProvider(this);
		}

		return pluginManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginRepositoriesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginRepositoriesTypeItemProvider pluginRepositoriesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginRepositoriesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginRepositoriesTypeAdapter() {
		if (pluginRepositoriesTypeItemProvider == null) {
			pluginRepositoriesTypeItemProvider = new PluginRepositoriesTypeItemProvider(this);
		}

		return pluginRepositoriesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginRepositoriesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginRepositoriesType1ItemProvider pluginRepositoriesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginRepositoriesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginRepositoriesType1Adapter() {
		if (pluginRepositoriesType1ItemProvider == null) {
			pluginRepositoriesType1ItemProvider = new PluginRepositoriesType1ItemProvider(this);
		}

		return pluginRepositoriesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginsTypeItemProvider pluginsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginsTypeAdapter() {
		if (pluginsTypeItemProvider == null) {
			pluginsTypeItemProvider = new PluginsTypeItemProvider(this);
		}

		return pluginsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginsType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginsType1ItemProvider pluginsType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginsType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginsType1Adapter() {
		if (pluginsType1ItemProvider == null) {
			pluginsType1ItemProvider = new PluginsType1ItemProvider(this);
		}

		return pluginsType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginsType2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginsType2ItemProvider pluginsType2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginsType2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginsType2Adapter() {
		if (pluginsType2ItemProvider == null) {
			pluginsType2ItemProvider = new PluginsType2ItemProvider(this);
		}

		return pluginsType2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PluginsType3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PluginsType3ItemProvider pluginsType3ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PluginsType3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPluginsType3Adapter() {
		if (pluginsType3ItemProvider == null) {
			pluginsType3ItemProvider = new PluginsType3ItemProvider(this);
		}

		return pluginsType3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Prerequisites} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrerequisitesItemProvider prerequisitesItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Prerequisites}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPrerequisitesAdapter() {
		if (prerequisitesItemProvider == null) {
			prerequisitesItemProvider = new PrerequisitesItemProvider(this);
		}

		return prerequisitesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Profile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProfileItemProvider profileItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Profile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProfileAdapter() {
		if (profileItemProvider == null) {
			profileItemProvider = new ProfileItemProvider(this);
		}

		return profileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ProfilesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProfilesTypeItemProvider profilesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ProfilesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProfilesTypeAdapter() {
		if (profilesTypeItemProvider == null) {
			profilesTypeItemProvider = new ProfilesTypeItemProvider(this);
		}

		return profilesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PropertiesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesTypeItemProvider propertiesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PropertiesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPropertiesTypeAdapter() {
		if (propertiesTypeItemProvider == null) {
			propertiesTypeItemProvider = new PropertiesTypeItemProvider(this);
		}

		return propertiesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PropertiesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesType1ItemProvider propertiesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PropertiesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPropertiesType1Adapter() {
		if (propertiesType1ItemProvider == null) {
			propertiesType1ItemProvider = new PropertiesType1ItemProvider(this);
		}

		return propertiesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PropertiesType2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesType2ItemProvider propertiesType2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PropertiesType2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPropertiesType2Adapter() {
		if (propertiesType2ItemProvider == null) {
			propertiesType2ItemProvider = new PropertiesType2ItemProvider(this);
		}

		return propertiesType2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.PropertiesType3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesType3ItemProvider propertiesType3ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.PropertiesType3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPropertiesType3Adapter() {
		if (propertiesType3ItemProvider == null) {
			propertiesType3ItemProvider = new PropertiesType3ItemProvider(this);
		}

		return propertiesType3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Relocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelocationItemProvider relocationItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Relocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRelocationAdapter() {
		if (relocationItemProvider == null) {
			relocationItemProvider = new RelocationItemProvider(this);
		}

		return relocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Reporting} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportingItemProvider reportingItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Reporting}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportingAdapter() {
		if (reportingItemProvider == null) {
			reportingItemProvider = new ReportingItemProvider(this);
		}

		return reportingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportPlugin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportPluginItemProvider reportPluginItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportPlugin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportPluginAdapter() {
		if (reportPluginItemProvider == null) {
			reportPluginItemProvider = new ReportPluginItemProvider(this);
		}

		return reportPluginItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportSetItemProvider reportSetItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportSetAdapter() {
		if (reportSetItemProvider == null) {
			reportSetItemProvider = new ReportSetItemProvider(this);
		}

		return reportSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportSetsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportSetsTypeItemProvider reportSetsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportSetsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportSetsTypeAdapter() {
		if (reportSetsTypeItemProvider == null) {
			reportSetsTypeItemProvider = new ReportSetsTypeItemProvider(this);
		}

		return reportSetsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportsTypeItemProvider reportsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportsTypeAdapter() {
		if (reportsTypeItemProvider == null) {
			reportsTypeItemProvider = new ReportsTypeItemProvider(this);
		}

		return reportsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportsType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportsType1ItemProvider reportsType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportsType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportsType1Adapter() {
		if (reportsType1ItemProvider == null) {
			reportsType1ItemProvider = new ReportsType1ItemProvider(this);
		}

		return reportsType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ReportsType2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportsType2ItemProvider reportsType2ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ReportsType2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReportsType2Adapter() {
		if (reportsType2ItemProvider == null) {
			reportsType2ItemProvider = new ReportsType2ItemProvider(this);
		}

		return reportsType2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.RepositoriesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoriesTypeItemProvider repositoriesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.RepositoriesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositoriesTypeAdapter() {
		if (repositoriesTypeItemProvider == null) {
			repositoriesTypeItemProvider = new RepositoriesTypeItemProvider(this);
		}

		return repositoriesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.RepositoriesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoriesType1ItemProvider repositoriesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.RepositoriesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositoriesType1Adapter() {
		if (repositoriesType1ItemProvider == null) {
			repositoriesType1ItemProvider = new RepositoriesType1ItemProvider(this);
		}

		return repositoriesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Repository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryItemProvider repositoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Repository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositoryAdapter() {
		if (repositoryItemProvider == null) {
			repositoryItemProvider = new RepositoryItemProvider(this);
		}

		return repositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.RepositoryPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryPolicyItemProvider repositoryPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.RepositoryPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositoryPolicyAdapter() {
		if (repositoryPolicyItemProvider == null) {
			repositoryPolicyItemProvider = new RepositoryPolicyItemProvider(this);
		}

		return repositoryPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Resource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceItemProvider resourceItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Resource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createResourceAdapter() {
		if (resourceItemProvider == null) {
			resourceItemProvider = new ResourceItemProvider(this);
		}

		return resourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ResourcesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourcesTypeItemProvider resourcesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ResourcesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createResourcesTypeAdapter() {
		if (resourcesTypeItemProvider == null) {
			resourcesTypeItemProvider = new ResourcesTypeItemProvider(this);
		}

		return resourcesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.ResourcesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourcesType1ItemProvider resourcesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.ResourcesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createResourcesType1Adapter() {
		if (resourcesType1ItemProvider == null) {
			resourcesType1ItemProvider = new ResourcesType1ItemProvider(this);
		}

		return resourcesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.RolesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolesTypeItemProvider rolesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.RolesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRolesTypeAdapter() {
		if (rolesTypeItemProvider == null) {
			rolesTypeItemProvider = new RolesTypeItemProvider(this);
		}

		return rolesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.RolesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolesType1ItemProvider rolesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.RolesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRolesType1Adapter() {
		if (rolesType1ItemProvider == null) {
			rolesType1ItemProvider = new RolesType1ItemProvider(this);
		}

		return rolesType1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Scm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScmItemProvider scmItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Scm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createScmAdapter() {
		if (scmItemProvider == null) {
			scmItemProvider = new ScmItemProvider(this);
		}

		return scmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.Site} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SiteItemProvider siteItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.Site}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSiteAdapter() {
		if (siteItemProvider == null) {
			siteItemProvider = new SiteItemProvider(this);
		}

		return siteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.TestResourcesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestResourcesTypeItemProvider testResourcesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.TestResourcesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTestResourcesTypeAdapter() {
		if (testResourcesTypeItemProvider == null) {
			testResourcesTypeItemProvider = new TestResourcesTypeItemProvider(this);
		}

		return testResourcesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.apache.maven.pom400.TestResourcesType1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestResourcesType1ItemProvider testResourcesType1ItemProvider;

	/**
	 * This creates an adapter for a {@link org.apache.maven.pom400.TestResourcesType1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTestResourcesType1Adapter() {
		if (testResourcesType1ItemProvider == null) {
			testResourcesType1ItemProvider = new TestResourcesType1ItemProvider(this);
		}

		return testResourcesType1ItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (activationItemProvider != null) activationItemProvider.dispose();
		if (activationFileItemProvider != null) activationFileItemProvider.dispose();
		if (activationOSItemProvider != null) activationOSItemProvider.dispose();
		if (activationPropertyItemProvider != null) activationPropertyItemProvider.dispose();
		if (buildItemProvider != null) buildItemProvider.dispose();
		if (buildBaseItemProvider != null) buildBaseItemProvider.dispose();
		if (ciManagementItemProvider != null) ciManagementItemProvider.dispose();
		if (configurationTypeItemProvider != null) configurationTypeItemProvider.dispose();
		if (configurationType1ItemProvider != null) configurationType1ItemProvider.dispose();
		if (configurationType2ItemProvider != null) configurationType2ItemProvider.dispose();
		if (configurationType3ItemProvider != null) configurationType3ItemProvider.dispose();
		if (configurationType4ItemProvider != null) configurationType4ItemProvider.dispose();
		if (contributorItemProvider != null) contributorItemProvider.dispose();
		if (contributorsTypeItemProvider != null) contributorsTypeItemProvider.dispose();
		if (dependenciesTypeItemProvider != null) dependenciesTypeItemProvider.dispose();
		if (dependenciesType1ItemProvider != null) dependenciesType1ItemProvider.dispose();
		if (dependenciesType2ItemProvider != null) dependenciesType2ItemProvider.dispose();
		if (dependenciesType3ItemProvider != null) dependenciesType3ItemProvider.dispose();
		if (dependencyItemProvider != null) dependencyItemProvider.dispose();
		if (dependencyManagementItemProvider != null) dependencyManagementItemProvider.dispose();
		if (deploymentRepositoryItemProvider != null) deploymentRepositoryItemProvider.dispose();
		if (developerItemProvider != null) developerItemProvider.dispose();
		if (developersTypeItemProvider != null) developersTypeItemProvider.dispose();
		if (distributionManagementItemProvider != null) distributionManagementItemProvider.dispose();
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (excludesTypeItemProvider != null) excludesTypeItemProvider.dispose();
		if (exclusionItemProvider != null) exclusionItemProvider.dispose();
		if (exclusionsTypeItemProvider != null) exclusionsTypeItemProvider.dispose();
		if (executionsTypeItemProvider != null) executionsTypeItemProvider.dispose();
		if (extensionItemProvider != null) extensionItemProvider.dispose();
		if (extensionsTypeItemProvider != null) extensionsTypeItemProvider.dispose();
		if (filtersTypeItemProvider != null) filtersTypeItemProvider.dispose();
		if (filtersType1ItemProvider != null) filtersType1ItemProvider.dispose();
		if (goalsTypeItemProvider != null) goalsTypeItemProvider.dispose();
		if (goalsType1ItemProvider != null) goalsType1ItemProvider.dispose();
		if (includesTypeItemProvider != null) includesTypeItemProvider.dispose();
		if (issueManagementItemProvider != null) issueManagementItemProvider.dispose();
		if (licenseItemProvider != null) licenseItemProvider.dispose();
		if (licensesTypeItemProvider != null) licensesTypeItemProvider.dispose();
		if (mailingListItemProvider != null) mailingListItemProvider.dispose();
		if (mailingListsTypeItemProvider != null) mailingListsTypeItemProvider.dispose();
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (modulesTypeItemProvider != null) modulesTypeItemProvider.dispose();
		if (modulesType1ItemProvider != null) modulesType1ItemProvider.dispose();
		if (notifierItemProvider != null) notifierItemProvider.dispose();
		if (notifiersTypeItemProvider != null) notifiersTypeItemProvider.dispose();
		if (organizationItemProvider != null) organizationItemProvider.dispose();
		if (otherArchivesTypeItemProvider != null) otherArchivesTypeItemProvider.dispose();
		if (parentItemProvider != null) parentItemProvider.dispose();
		if (pluginItemProvider != null) pluginItemProvider.dispose();
		if (pluginExecutionItemProvider != null) pluginExecutionItemProvider.dispose();
		if (pluginManagementItemProvider != null) pluginManagementItemProvider.dispose();
		if (pluginRepositoriesTypeItemProvider != null) pluginRepositoriesTypeItemProvider.dispose();
		if (pluginRepositoriesType1ItemProvider != null) pluginRepositoriesType1ItemProvider.dispose();
		if (pluginsTypeItemProvider != null) pluginsTypeItemProvider.dispose();
		if (pluginsType1ItemProvider != null) pluginsType1ItemProvider.dispose();
		if (pluginsType2ItemProvider != null) pluginsType2ItemProvider.dispose();
		if (pluginsType3ItemProvider != null) pluginsType3ItemProvider.dispose();
		if (prerequisitesItemProvider != null) prerequisitesItemProvider.dispose();
		if (profileItemProvider != null) profileItemProvider.dispose();
		if (profilesTypeItemProvider != null) profilesTypeItemProvider.dispose();
		if (propertiesTypeItemProvider != null) propertiesTypeItemProvider.dispose();
		if (propertiesType1ItemProvider != null) propertiesType1ItemProvider.dispose();
		if (propertiesType2ItemProvider != null) propertiesType2ItemProvider.dispose();
		if (propertiesType3ItemProvider != null) propertiesType3ItemProvider.dispose();
		if (relocationItemProvider != null) relocationItemProvider.dispose();
		if (reportingItemProvider != null) reportingItemProvider.dispose();
		if (reportPluginItemProvider != null) reportPluginItemProvider.dispose();
		if (reportSetItemProvider != null) reportSetItemProvider.dispose();
		if (reportSetsTypeItemProvider != null) reportSetsTypeItemProvider.dispose();
		if (reportsTypeItemProvider != null) reportsTypeItemProvider.dispose();
		if (reportsType1ItemProvider != null) reportsType1ItemProvider.dispose();
		if (reportsType2ItemProvider != null) reportsType2ItemProvider.dispose();
		if (repositoriesTypeItemProvider != null) repositoriesTypeItemProvider.dispose();
		if (repositoriesType1ItemProvider != null) repositoriesType1ItemProvider.dispose();
		if (repositoryItemProvider != null) repositoryItemProvider.dispose();
		if (repositoryPolicyItemProvider != null) repositoryPolicyItemProvider.dispose();
		if (resourceItemProvider != null) resourceItemProvider.dispose();
		if (resourcesTypeItemProvider != null) resourcesTypeItemProvider.dispose();
		if (resourcesType1ItemProvider != null) resourcesType1ItemProvider.dispose();
		if (rolesTypeItemProvider != null) rolesTypeItemProvider.dispose();
		if (rolesType1ItemProvider != null) rolesType1ItemProvider.dispose();
		if (scmItemProvider != null) scmItemProvider.dispose();
		if (siteItemProvider != null) siteItemProvider.dispose();
		if (testResourcesTypeItemProvider != null) testResourcesTypeItemProvider.dispose();
		if (testResourcesType1ItemProvider != null) testResourcesType1ItemProvider.dispose();
	}

}
