/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ActivationFile;
import org.apache.maven.pom400.ActivationOS;
import org.apache.maven.pom400.ActivationProperty;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Activation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivationValidator {
	boolean validate();

	boolean validateActiveByDefault(boolean value);
	boolean validateJdk(String value);
	boolean validateOs(ActivationOS value);
	boolean validateProperty(ActivationProperty value);
	boolean validateFile(ActivationFile value);
}
