/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ExtensionsType;
import org.apache.maven.pom400.FiltersType1;
import org.apache.maven.pom400.PluginManagement;
import org.apache.maven.pom400.PluginsType2;
import org.apache.maven.pom400.ResourcesType1;
import org.apache.maven.pom400.TestResourcesType1;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Build}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BuildValidator {
	boolean validate();

	boolean validateSourceDirectory(String value);
	boolean validateScriptSourceDirectory(String value);
	boolean validateTestSourceDirectory(String value);
	boolean validateOutputDirectory(String value);
	boolean validateTestOutputDirectory(String value);
	boolean validateExtensions(ExtensionsType value);
	boolean validateDefaultGoal(String value);
	boolean validateResources(ResourcesType1 value);
	boolean validateTestResources(TestResourcesType1 value);
	boolean validateDirectory(String value);
	boolean validateFinalName(String value);
	boolean validateFilters(FiltersType1 value);
	boolean validatePluginManagement(PluginManagement value);
	boolean validatePlugins(PluginsType2 value);
}
