/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.FiltersType;
import org.apache.maven.pom400.PluginManagement;
import org.apache.maven.pom400.PluginsType;
import org.apache.maven.pom400.ResourcesType;
import org.apache.maven.pom400.TestResourcesType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.BuildBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BuildBaseValidator {
	boolean validate();

	boolean validateDefaultGoal(String value);
	boolean validateResources(ResourcesType value);
	boolean validateTestResources(TestResourcesType value);
	boolean validateDirectory(String value);
	boolean validateFinalName(String value);
	boolean validateFilters(FiltersType value);
	boolean validatePluginManagement(PluginManagement value);
	boolean validatePlugins(PluginsType value);
}
