/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.PropertiesType;
import org.apache.maven.pom400.RolesType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Contributor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContributorValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateEmail(String value);
	boolean validateUrl(String value);
	boolean validateOrganization(String value);
	boolean validateOrganizationUrl(String value);
	boolean validateRoles(RolesType value);
	boolean validateTimezone(String value);
	boolean validateProperties(PropertiesType value);
}
