/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ExclusionsType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Dependency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependencyValidator {
	boolean validate();

	boolean validateGroupId(String value);
	boolean validateArtifactId(String value);
	boolean validateVersion(String value);
	boolean validateType(String value);
	boolean validateClassifier(String value);
	boolean validateScope(String value);
	boolean validateSystemPath(String value);
	boolean validateExclusions(ExclusionsType value);
	boolean validateOptional(boolean value);
}
