/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.DeploymentRepository;
import org.apache.maven.pom400.Relocation;
import org.apache.maven.pom400.Site;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.DistributionManagement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DistributionManagementValidator {
	boolean validate();

	boolean validateRepository(DeploymentRepository value);
	boolean validateSnapshotRepository(DeploymentRepository value);
	boolean validateSite(Site value);
	boolean validateDownloadUrl(String value);
	boolean validateRelocation(Relocation value);
	boolean validateStatus(String value);
}
