/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.OtherArchivesType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.MailingList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MailingListValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSubscribe(String value);
	boolean validateUnsubscribe(String value);
	boolean validatePost(String value);
	boolean validateArchive(String value);
	boolean validateOtherArchives(OtherArchivesType value);
}
