/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ConfigurationType3;
import org.apache.maven.pom400.GoalsType1;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.PluginExecution}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PluginExecutionValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validatePhase(String value);
	boolean validateGoals(GoalsType1 value);
	boolean validateInherited(String value);
	boolean validateConfiguration(ConfigurationType3 value);
}
