/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ConfigurationType2;
import org.apache.maven.pom400.DependenciesType3;
import org.apache.maven.pom400.ExecutionsType;
import org.apache.maven.pom400.GoalsType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Plugin}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PluginValidator {
	boolean validate();

	boolean validateGroupId(String value);
	boolean validateArtifactId(String value);
	boolean validateVersion(String value);
	boolean validateExtensions(boolean value);
	boolean validateExecutions(ExecutionsType value);
	boolean validateDependencies(DependenciesType3 value);
	boolean validateGoals(GoalsType value);
	boolean validateInherited(String value);
	boolean validateConfiguration(ConfigurationType2 value);
}
