/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.ConfigurationType;
import org.apache.maven.pom400.ReportSetsType;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.ReportPlugin}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReportPluginValidator {
	boolean validate();

	boolean validateGroupId(String value);
	boolean validateArtifactId(String value);
	boolean validateVersion(String value);
	boolean validateInherited(String value);
	boolean validateConfiguration(ConfigurationType value);
	boolean validateReportSets(ReportSetsType value);
}
