/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.apache.maven.pom400.validation;

import org.apache.maven.pom400.PluginsType1;

/**
 * A sample validator interface for {@link org.apache.maven.pom400.Reporting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReportingValidator {
	boolean validate();

	boolean validateExcludeDefaults(boolean value);
	boolean validateOutputDirectory(String value);
	boolean validatePlugins(PluginsType1 value);
}
